import React, { useState } from "react";
import Loader from "./Loader";
import { useEffect } from "react";
import axios from "axios";
// import { profileImage } from "../assests/profile.png";
import { ArrowDownFromLine, UserCircle2 } from "lucide-react";

function Home() {
  const [myPostData, setMyPostData] = useState([]);

  // fetch post api call

  const ServerUrl = "https://ai-imagegenerator-backend.onrender.com";
  const postApi = async () => {
    const resp = await axios.get(`${ServerUrl}/api/v1/post`);
    const { data } = resp.data;
    setMyPostData(data);
  };

  const downloadHandler = (url) => {
    // preventDefault()
    console.log(url, "this is url");
    const anchor = document.createElement("a");
    anchor.href = url;

    anchor.download = "image.jpg";

    anchor.click();
  };

  useEffect(() => {
    postApi();
  }, []);

  // console.log(myPostData);

  return (
    <section className="py-4 px-4 sm:px-12">
      <h1 className="my-2">The Community Showcase</h1>
      <p className="my-2">
        Browse through a collection of imaginative and visually stunning images
        generated by DALL-E AI.
      </p>

      <div className="mt-16">
        <h6>Search posts</h6>
        <input
          type="text"
          name="seacrhFilter"
          id="seacrhFilter"
          placeholder="Search posts"
          className="border  rounded-lg w-full outline-none px-4 py-1 font-[14px] my-2"
        />
      </div>

      {myPostData.length > 1 ? (
        <section className="sm:grid sm:grid-cols-2 lg:grid-cols-3 gap-6 mt-12 sm:my-0  ">
          {myPostData.map((post, index) => (
            <div
              key={index}
              className="relative my-8 group transition-all ease-in-out border-gray-400 border-[1px] shadow-lg shadow-gray-300"
            >
              <img
                src={post.photo}
                alt="post"
                className="bg-white mix-blend-darken"
              />
              <div className="w-[100%] absolute bottom-0 p-4 bg-[#060606e3] hidden transition ease-in-out delay-500 group-hover:block duration-300">
                <p className="font-bold capitalize">{post.prompt}</p>
                <div className="flex items-center gap-2 mt-2">
                  <UserCircle2
                    strokeWidth={1.75}
                    className="w-10  text-white"
                  />
                  <p className="text-sm capitalize font-[300]">{post.name}</p>

                  <ArrowDownFromLine
                    strokeWidth={3}
                    className="absolute right-4 bottom-4  border-none w-8 cursor-pointer  text-white"
                    onClick={() => downloadHandler(post.photo)}
                  />
                </div>
              </div>
            </div>
          ))}

          <div className="p-4 border-blue-400 rounded-xl"></div>
        </section>
      ) : (
        <span className="w-full bg-slate-700 h-52">
          <Loader />
        </span>
      )}

      <hr class="bg-gray-100 h-[2px] mt-2" />
      <footer className=" grid place-items-center w-full bg-gray-50 py-4 -mb-4">
        <h6>
          This is an AI image Generator made with the help of OpenAi Api for my
          personal learning purpose.
        </h6>
        <h3 className="my-3">Made By Developer Dikshant🦋</h3>
      </footer>
    </section>
  );
}

export default Home;
